### ISSUE TITLE
Create a copy to clipboard button

### ISSUE THREAD

**Issue by augusto-jm-amaral** [augusto-jm-amaral/json-prettier-app#1]
### Description
This button allows the users to copy the editor data.

You can use https://clipboardjs.com/.

**Comment by Abhikumar98** [comment]
@augusto-jm-amaral I can take this up.

**Comment by amrutsabale** [comment]
hey ..i can make this change and raise PR

**Comment by amrutsabale** [comment]
I am doing this way, what do you think?
```javascript
 useEffect(() => {
    const clipboard = new Clipboard(".copyButton", {
      text: () => text,
    })
    return () => clipboard.destroy()
  }, [text])
```
```<a  href='#' className='copyButton'>```

**Comment by bhantsi** [comment]
Let me try this

**Comment by augusto-jm-amaral** [comment]
Thank you @amrutsabale
