### ISSUE TITLE
Repository link on web App

### ISSUE THREAD

**Issue by augusto-jm-amaral** [augusto-jm-amaral/json-prettier-app#2]
What do you think if you add a repository link on the web App?

Like this: 
React
<img width="97" alt="Screen Shot 2020-10-18 at 3 00 41 PM" src="https://user-images.githubusercontent.com/10222646/96375995-cbda3d80-1152-11eb-8f3b-4297ab9ac406.png">

Sequelize
<img width="48" alt="Screen Shot 2020-10-18 at 3 00 48 PM" src="https://user-images.githubusercontent.com/10222646/96375997-cd0b6a80-1152-11eb-88c9-079979dbfd40.png">

Jest
<img width="78" alt="Screen Shot 2020-10-18 at 3 01 03 PM" src="https://user-images.githubusercontent.com/10222646/96375999-cd0b6a80-1152-11eb-9e1a-026c08d39b4c.png">

This change will help the users to contribute to the project.

**Comment by Jeconias** [comment]
You can assign it to me?

**Comment by augusto-jm-amaral** [comment]
Done @Jeconias

**Comment by augusto-jm-amaral** [comment]
Thank you @Jeconias
